# Generated by Django 2.2.6 on 2019-10-21 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wirecardbackend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Client',
        ),
    ]
