# Generated by Django 2.2.6 on 2019-10-22 01:09

import creditcards.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wirecardbackend', '0002_auto_20191021_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('CPF', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=16)),
                ('expiration_date', creditcards.models.CardExpiryField(verbose_name='expiration date')),
                ('CVV', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Type', models.CharField(choices=[(1, 'Boleto'), (2, 'Cartão')], max_length=1)),
                ('Card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wirecardbackend.Card')),
            ],
        ),
    ]
