# Generated by Django 2.2.6 on 2019-10-22 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wirecardbackend', '0003_buyer_card_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
