# Generated by Django 2.2.6 on 2019-10-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirecardbackend', '0004_delete_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
