# Generated by Django 2.2.6 on 2019-10-23 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wirecardbackend', '0005_client'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buyer',
            table='buyer',
        ),
    ]
