# Generated by Django 2.2.6 on 2019-10-23 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirecardbackend', '0007_payment_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Payment_status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
