# Generated by Django 2.2.6 on 2019-10-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirecardbackend', '0009_auto_20191023_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Status',
            field=models.BooleanField(choices=[(1, 'Ativo'), (0, 'Inativo')], default=True),
            preserve_default=False,
        ),
    ]
