# Generated by Django 2.2.6 on 2019-10-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirecardbackend', '0011_auto_20191023_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='CPF',
            new_name='cpf',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='CVV',
            new_name='cvv',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='Status',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Card',
            new_name='card',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Client_id',
            new_name='client_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Payment_status',
            new_name='payment_status',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='payment',
            name='boleto_number',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
