# Generated by Django 2.2.6 on 2019-10-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wirecardbackend', '0012_auto_20191023_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='boleto_number',
            field=models.IntegerField(null=True),
        ),
    ]
