# Generated by Django 2.2.6 on 2019-10-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wirecardbackend', '0013_auto_20191023_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='boleto_number',
        ),
    ]
